server:
  port: 8080
  servlet:
    context-path: /mcp

spring:
  application:
    name: mcp-server-postgresql

  # Cache configuration with extended expiration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=120m
    cache-names:
      - plans
      - templates
      - sdk-configs
      - project-context
      - standards

  # Jackson configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false

  # Freemarker configuration
  freemarker:
    template-loader-path: classpath:/templates/
    charset: UTF-8
    cache: true
    suffix: .ftl

# MCP Server Configuration
mcp:
  server:
    name: "PostgreSQL Integration MCP Server"
    version: "1.0.0"
    capabilities:
      - postgresql
      - database-integration
      - code-generation

  sdk:
    base-path: ./sdk-repositories
    cache-enabled: true
    default-sdk: postgresql-java-sdk

  standards:
    base-path: ./coding-standards
    default-standard: java-spring-boot

  generation:
    default-package: com.example
    use-lombok: true
    include-validation: true
    include-tests: false
    naming-strategy: snake_case

  plan:
    expiration-minutes: 120  # Extended to 2 hours
    max-cached-plans: 1000

# Logging configuration with enhanced debugging
logging:
  level:
    root: INFO
    com.mcp: DEBUG
    com.mcp.server.controller: TRACE
    com.mcp.server.service: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.cache: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mcp-server.log
    max-size: 10MB
    max-history: 10

# Enable actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches
  endpoint:
    health:
      show-details: always